services:
    postgres:
      image: postgres
      restart: always
      volumes:
        - postgres-data:/data/db
      environment:
        - 'POSTGRES_USER=eagles'
        - 'POSTGRES_DB=eagles'
        - 'POSTGRES_PASSWORD=password'
      ports:
        - 5432:5432
volumes:
  postgres-data: